version: '3.0.0'
services:
  db:
    image: mongo:latest
    container_name: my-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MongoAdmin
      - MONGO_INITDB_ROOT_PASSWORD=test123
      - MONGO_INITDB_DATABASE=devissuetracker
    ports:
      - '5432:5432'
