version: '3.8'

networks:
  issuetracker-network:

services:
  db:
    image: mongo:latest
    
    container_name: my-mongodb

    restart: always

    environment:
      - MONGO_INITDB_ROOT_USERNAME=course
      - MONGO_INITDB_ROOT_PASSWORD=whatever
      - MONGO_INITDB_DATABASE=db

    ports:
      - '27017:27017'

    networks:
      - issuetracker-network
