---

name: '.NET code metrics'

permissions:
  contents: read

'on':
  push:
    branches:
      - main
    paths-ignore:
      - 'CODE_METRICS.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'CODE_METRICS.md'

  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: 'Print manual run reason'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo 'Reason: ${{ github.event.inputs.reason }}'
      - name: .NET code metrics
        id: dotnet-code-metrics
        uses: dotnet/samples/github-actions/DotNet.GitHubAction@19e8c4e6ee276a5a8caff42ef3b508045d751b7b
        env:
          GREETINGS: 'Hello, .NET developers!'  # ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ github.event.repository.name }}
          branch: ${{ github.ref }}
          dir: './'

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8.1.1
        if: ${{ steps.dotnet-code-metrics.outputs.updated-metrics == 'true' && github.event_name != 'pull_request' && github.ref != 'refs/heads/main' }}
        with:
          title: '${{ steps.dotnet-code-metrics.outputs.summary-title }}'
          body: '${{ steps.dotnet-code-metrics.outputs.summary-details }}'
          commit-message: '.NET code metrics, automated pull request.'
          base: main
          branch: automated/code-metrics
